name: CI Build

on:
  push:
    branches: [ dev ]
#  pull_request:
#    branches: [ master ]

jobs:
  ci-build:
    name: CI Build
    runs-on: macOS-latest #ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      # sets up .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        
      - name: Install Dependencies
        run: dotnet restore
      
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
      
      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal
